### ISSUE TITLE
found vulnerabilities

### ISSUE THREAD

**Issue by ZexuanTHU** [WeebDev/lolisafe#166]
After clone this repo and exec `npm install`, there is a warning existed say that
```shell
added 600 packages from 432 contributors and audited 2022 packages in 26.486s
found 11 vulnerabilities (1 low, 9 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Ignore it and enter `node lolisafe.js`, got an error message
```shell
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/root/lolisafe/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/lolisafe/lolisafe.js:58:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by Aareksio** [comment]
`EADDRINUSE` - you already have other app listening on `8080`

**Comment by RyoshiKayo** [comment]
@ZexuanTHU Are you using NGINX as a reverse proxy? If so you should change the port in the lolisafe config to something like 9696. Just make sure to update the NGINX configuration to reflect that. This is all documented in the README.md.

**Comment by RyoshiKayo** [comment]
The NPM errors are because the packages are out of date.
