### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by formatme** [WeebDev/lolisafe#45]
/home/formatme/test/lolisafe.js:21
let limiter = new RateLimit({ windowMs: 5000, max: 2 })
    ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by formatme** [comment]
if i remove it i get 
safe.get('/a/:identifier', (req, res, next) => res.sendFile('album.html', { ro
                                             ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by KyeNormanGill** [comment]
What version of node are you using.

**Comment by iCrawl** [comment]
You should run at least node LTS, which is version 6.

**Comment by formatme** [comment]
i was running node 10, switched to node 7 and it works now.

**Comment by iCrawl** [comment]
You mean 0.10 😄
